<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_SellerSubAccount
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

 $isPartner = $block->getLayout()->createBlock(
     \Webkul\SellerSubAccount\Block\SubAccount::class
 )->_mpHelper->isSeller();
 $viewModel = $block->getViewModel();
    ?>
<?php if ($isPartner == 1): ?>
    <legend class="legend wk-mp-legend">
        <span><?= $block->escapeHtmlAttr(__("Manage Sub Accounts"));?></span>
    </legend>
    <div class="wk-ui-component-container">
        <?php if ($viewModel->checkPermission("Webkul_SellerSubAccount::management") != 0 &&
        $viewModel->checkPermission("Webkul_SellerSubAccount::manage") != 0): ?>
        <div class="page-main-actions-sub-account">
            <div class="page-actions-placeholder"></div>
            <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                <div class="page-actions-inner" data-title='<?=$block->escapeHtmlAttr(__("Manage Sub Account")); ?>'>
                    <div class="page-actions-buttons">
                        <button id="add" title='<?=$block->escapeHtmlAttr(__("Add New Sub Account")); ?>'
                        type="button" class="primary-btn rounded line-height-15" onclick="location.href =
                        '<?=$block->escapeUrl($block->getUrl('sellersubaccount/account/new'));?>';"
                        data-ui-id="add-button">
                            <span><?=$block->escapeHtml(__("Create New Sub-account")); ?></span>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <?php endif;?>
        <?=$block->getChildHtml(); ?>
    </div>
<?php else: ?>
    <h2 class="wk-mp-error-msg">
        <?=$block->escapeHtmlAttr(__("To Become Seller Please Contact to Admin.")); ?>
    </h2>
<?php endif; ?>