<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Review\Block\Product\Review $block */
?>
<div class="review_section">
    <div class="left_section">
        <?= $block->getChildHtml('review.info.list'); ?>
        <?= $block->getChildHtml('review_form'); ?>
    </div>
    <div class="right_section">
        <div id="product-review-container" data-role="product-review"></div>
    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
