<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\Marketplace\Block\Product\Create */
?>
<div class="wk-mp-product-container">
    <br>    
    <i class="container-hide-show close">
        <label class="label"><?= $escaper->escapeHtml(__('Related Products, Up-Sells, and Cross-Sells')) ?></label>
    </i>
    <hr>
    <div class="wk-mp-new-prod-fields _hide">
        <?= $block->getChildHtml(); ?>
    </div>
</div>