<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of object manager
    $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
    $connection = $resource->getConnection();
    $select = $connection->select()
        ->from('customer_entity')
        ->where('group_id = 4')
        ->where('is_active!=3');

$result = $connection->fetchAll($select);

// die();
?>

<!-- <h1>Welcome to your custom module!</h1> -->
<table class="view-table">
  <tr>
    <th>ID</th>
    <th>Email</th>
    <th>Business Name</th>
    <th>Phone Number</th>
    <th>Address</th>
    <th>Sales Size</th>
    <th>Business Area</th>
    <th>Tax Id</th>
    <th>Action</th>
  </tr>
  <?php foreach ($result as $id => $rowData) {?>
    <tr>
      <td><?php echo $rowData['entity_id']; ?></td>
      <td><?php echo $rowData['email']; ?></td>
      <td><?php echo $rowData['business_name']; ?></td>
      <td><?php echo $rowData['phone_number']; ?></td>
      <td><?php echo $rowData['address']; ?></td>
      <td><?php echo $rowData['sales_size']; ?></td>
      <td><?php echo $rowData['business_area']; ?></td>
      <td><?php echo $rowData['tax_id']; ?></td>
      <td>
      <?php if($rowData['is_active']==0){ ?><button onclick="approve('<?php echo $rowData['entity_id']; ?>','approve')">Approve</button><?php } else if($rowData['is_active']==1) { ?>
        <a href="#" onclick="approve('<?php echo $rowData['entity_id']; ?>','decline')">Decline</a>
        <?php } ?>
        <a href="<?php echo $block->getUrl('adminmenu/create/geteditdata') ?>')">Edit</a>
      </td>
    </tr>
  <?php } ?>
</table>
<style>
.view-table {
    width: 100%;
    border-collapse: collapse;
}

.view-table th,
.view-table td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

.view-table th {
    background-color: #f2f2f2;
    font-weight: bold;
}
</style>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script type="text/javascript">
    // require([
    //     'jquery'
    // ])
    
    
    // function ($) {
      function approve(id,action){
        var url = '<?php echo $block->getUrl('adminmenu/create/updatedata') ?>';
          var formKey = '<?php echo $block->getFormKey() ?>';
          var postData = {
                id: id,
                action:action
            };
          $.ajax({
              url: url,
              type: 'GET',
                dataType: 'json',
                data: postData,
                contentType: 'application/x-www-form-urlencoded',
              showLoader: true,
              success: function (response) {
                window.location.reload()
                  console.log(response);
              }
          });
        }
        $(document).ready(function () {
          
        });
    // }
</script>