    <style>
        .popup-container {
                display:none;
                width:500px;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.7);
            z-index: 9999;
        }

        .popup-content {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
        }

        .popup-content h2 {
            margin-top: 0;
        }

        .action-close {
            margin-top: 10px;
        }
        .solum-st1 {
            background: #f3f2f2;
            padding: 14px;
        }
        .solum-st1 > ul > li
        {
            line-height: 2em;
        }
        /* input[type="text"] {
            padding: 8px;
            width: 300px;
        } */
        button {
            padding: 8px;
            width: 44px;
        }
        span.solum-st2 {
            float: left;
            color: #5e5e9a;
            font-size: 12px;
            font-weight: 600;
        }
        span.solum-st3 {
            float: right;
            color: #5e5e9a;
            font-size: 12px;
            font-weight: 600;
        }
        .solum-st4
        {
            font-size: 13px;
            color: #5e5e9a;
            font-weight: 600;
        }
        .customer_rfq_label{
            color:black
        }
        .rfqSelect{
            height: 45px;
            padding: 22px 8px;
            margin: 6px 0px;
            border-radius: 10px;
            border: 2px solid #ccc;
        }

    </style>
        <?php 
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $productCollection = $objectManager->create('\Magento\Catalog\Model\ResourceModel\Product\Collection');
            $productCollection->addAttributeToSelect('*'); // You can specify the attributes you want to load
            // $productCollection->addFieldToFilter('created_by','28');
            $params = $this->getRequest()->getParams();
        ?>
            <?php if ($block->showButton()): ?>
                <span class="solum-st3"><a onclick="openPopup()" style="background-color: #1979c3;padding: 6px 9px 6px 9px;border-radius: 5px;color: white;cursor:pointer;">Request for RFQ</a></span>
            <?php endif; ?>
            <div class="popup-container" id="customerrfqPopup" style="cursor:pointer;">
                <div class="popup-content">
                    <form method="post" action="<?= $block->getUrl('customerrfq/index/saverfq'); ?>" enctype="multipart/form-data">
                        <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
                        <input type="hidden" name="customer_id" value="<?php echo $block->getCustomerId() ?>" />
                        <input type="hidden" name="partner_id" id="partner_id" value="" />
                        <input type="hidden" name="status" id="status" value="Open" />

                        <label class="customer_rfq_label" for="product_name">Product:</label><br>
                        <select name="product_id" class="rfqSelect" onchange="productSelect(this.options[this.selectedIndex].getAttribute('test'))">
                        <?php foreach ($productCollection as $product) : ?>
                            <option test="<?php echo $product->getCreatedBy(); ?>" value="<?php echo $block->escapeHtml($product->getId()); ?>"><?php echo $block->escapeHtml($product->getName()); ?></option>
                            <?php endforeach; ?>
                        </select>
                        <!-- <input type="text" id="product_name" name="product_name" required /><br> -->

                        <label class="customer_rfq_label" for="product_price">No Of Stores:</label>
                        <input type="number" id="no_of_stores" name="no_of_stores" required /><br>

                        <label class="customer_rfq_label" for="product_price">Quantity Per Store:</label>
                        <input type="number" id="qty_per_store" name="quantity_per_store" required /><br>
                        <label class="customer_rfq_label" for="product_price">Comment:</label>
                        <input type="text" id="comment" name="comment" required /><br>
                        <button class="action-close" style="float:left" onclick="closePopup()">Close</button> <button type="submit" style="width: 40%;float: right;margin-top: 10px;background-color: #00203f;color: white;">Create Product</button>
                    </form>
                    <!-- Add more seller details as needed -->
                    
                </div>
            </div>
<script>
    function productSelect(test){
        document.getElementById('partner_id').value=test;
    }
  function openPopup() {
    var popup = document.getElementById('customerrfqPopup');
    popup.style.display = 'block';
}

function closePopup() {
    var popup = document.getElementById('customerrfqPopup');
    popup.style.display = 'none';
}
</script>
