<?php 
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
$viewModel = $block->getViewModel();
$language = $viewModel->getSwitcherBlockObject();
$languageViewModel = $viewModel->getSwitcherViewModel();
$currency = $viewModel->getCurrencyBlockObject();
$currencyFactory = $viewModel->getCurrencyModelFactory();
?>
    
        </ul>
        <div class="right-panel">
            <div class="language-box">            
                <?php if (count($language->getStores())>1) : ?>
                    <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''; ?>
                    <div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?= $language->escapeHtmlAttr($id) ?>">
                        <strong class="label switcher-label"><span><?= $language->escapeHtml(__('Language')) ?></span></strong>
                        <div class="actions dropdown options switcher-options">
                            <div class="action toggle switcher-trigger"
                                id="switcher-language-trigger<?= $language->escapeHtmlAttr($id) ?>"
                                data-mage-init='{"dropdown":{}}'
                                data-toggle="dropdown"
                                data-trigger-keypress-button="true">
                                <strong class="view-<?= $language->escapeHtml($language->getCurrentStoreCode()) ?>">
                                    <span><?= $language->escapeHtml($language->getCurrentStoreCode()) ?></span>
                                </strong>
                            </div>
                            <ul class="dropdown switcher-dropdown"
                                data-target="dropdown">
                                <?php foreach ($language->getStores() as $_lang) : ?>
                                    <li class="view-<?= $language->escapeHtml($_lang->getCode()) ?> switcher-option <?php if ($_lang->getId() == $language->getCurrentStoreId()) { ?> active <?php } ?>">                                                                            
                                        <a href="<?= $language->escapeUrl($languageViewModel->getTargetStoreRedirectUrl($_lang)) ?>">
                                            <?= $language->escapeHtml($_lang->getCode()) .' - '. $language->escapeHtml($_lang->getName()) ?>
                                        </a>
                                    </li>   
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                <?php endif; ?>          
            </div>
            <?php if ($currency->getCurrencyCount() > 1) : ?>
                <?php $currentCurrencyCode = $currency->getCurrentCurrencyCode(); ?>
            <div class="currency">
                <div class="currency-icon"><?= $currencyFactory->create()->load($currentCurrencyCode)->getCurrencySymbol(); ?></div>                  
                <?php $currencies = $currency->getCurrencies(); ?>                
                <?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : '' ?>
                <div class="switcher currency switcher-currency" id="switcher-currency<?= $currency->escapeHtmlAttr($id) ?>">
                    <strong class="label switcher-label"><span><?= $currency->escapeHtml(__('Currency')) ?></span></strong>
                    <div class="actions dropdown options switcher-options">
                        <div class="action toggle switcher-trigger"
                            id="switcher-currency-trigger<?= $currency->escapeHtmlAttr($id) ?>"
                            data-mage-init='{"dropdown":{}}'
                            data-toggle="dropdown"
                            data-trigger-keypress-button="true">
                            <strong class="language-<?= $currency->escapeHtml($currency->getCurrentCurrencyCode()) ?>">
                                <span><?= $currency->escapeHtml($currentCurrencyCode) ?></span>
                            </strong>
                        </div>
                        <ul class="dropdown switcher-dropdown" data-target="dropdown">
                            <?php foreach ($currencies as $_code => $_name) : 
                                $currencySymbol = $currencyFactory->create()->load($_code)->getCurrencySymbol();
                                ?>
                                <li class="currency-<?= $block->escapeHtmlAttr($_code) ?> switcher-option <?php if ($_code == $currentCurrencyCode){?> active <?php } ?>">                                 
                                    <a href="#" data-post='<?= /* @noEscape */ $currency->getSwitchCurrencyPostData($_code) ?>'>
                                        <div class="currency-detail">
                                            <span class="currency-name"><?= $currency->escapeHtml($_name) ?></span>
                                            <span class="currency-code"><?= $currency->escapeHtml($_code) ?> - <?= $currencySymbol ?? '$'; ?> </span>
                                        </div>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>  
            </div>
            <?php endif; ?> 
        </div>
    </nav>
</div>