<nav class="navigation" data-action="navigation">
        <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
            <li class="level0 category-item level-top">
                <a href="<?= $block->escapeUrl($block->getUrl('storepage'));?>" class="level-top direct-link">
                    <span><?= __('Store'); ?></span>
                </a>
            </li>