<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<?php
    $_helper = $block->getMpHelper();
    $isPartner= $_helper->isSeller();
    $magentoCurrentUrl = $block->getCurrentUrl();
    $allow_pro_type=$_helper->getAllowedProductType();
    $isSellerGroup = $_helper->isSellerGroupModuleInstalled();
    $productNotificationCount = $block->getProductNotificationCount();
    $orderNotificationCount = $block->getOrderNotificationCount();
    $transactionCount = $block->getTransactionNotificationCount();
    $viewModel = $block->getViewModel();
?>
<nav data-mage-init='{"Webkul_Marketplace/js/sellerNavigation": {}}' class="wk-mp-menu wk-mp-main">
    <ul id="wk-mp-nav">
        <?php if ($isPartner): ?>
            <?php if ($viewModel->checkPermission("Webkul_Marketplace::dashboard") > -1 && $_helper->isAllowed('marketplace/account/dashboard')): ?>
                <li class="wk-mp-item-dashboard level-0 
                <?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/account/dashboard')
                ? "current active":"";?>" id="wk-mp-menu-dashboard" >
                    <a href="<?= $escaper->escapeUrl($block
                    ->getUrl('marketplace/account/dashboard', ['_secure' => $block
                    ->getRequest()->isSecure()])); ?>" 
                    class="<?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/account/dashboard')
                    ? "active":"";?>">
                        <span><?= /* @noEscape */ __('Dashboard') ?></span>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ($viewModel->checkPermission("Webkul_Marketplace::orders") > -1 && $_helper->isAllowed('marketplace/order/history')): ?>
                <li class="nav item notification-link wk-mp-item-order level-0 
                <?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/order')
                && (!strpos($magentoCurrentUrl, 'marketplace/order/shipping/'))
                ? "current active":"";?>" id="wk-mp-menu-order" >
                    <a href="<?= $escaper->escapeUrl($block
                    ->getUrl('marketplace/order/history', ['_secure' => $block
                    ->getRequest()->isSecure()])); ?>" 
                    class="<?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/order')
                     && (!strpos($magentoCurrentUrl, 'marketplace/order/shipping/'))? "active":"";?>">
                        <span><?= /* @noEscape */ __('Orders') ?></span>
                    </a>
                </li>
            <?php endif; ?>
            <?php
                $actions = ["marketplace/product/add", "marketplace/product/productlist",
                "marketplace/product_attribute/new"];
                ?>
            <?php if ($viewModel->checkPermission("Webkul_Marketplace::products") > -1 && $_helper->isAllowed($actions)): ?>
                <li class="wk-mp-item-product level-0 <?= /* @noEscape */
                strpos($magentoCurrentUrl, 'marketplace/product/')? "current active":"";?>"
                 id="wk-mp-menu-product">
                    <a href="#" onclick="return false;" class="">
                        <span><?= /* @noEscape */ __('Products')?></span>
                    </a>
                    <div class="wk-mp-submenu">
                        <strong class="wk-mp-submenu-title"><?= /* @noEscape */ __('Products')?></strong>
                        <a href="#" class="action-close _close" data-role="wk-mp-close-submenu"></a>
                        <ul>
                            <li data-ui-id="menu-webkul-marketplace-menu" class="item-menu parent level-1">
                                <strong class="wk-mp-submenu-group-title">
                                    <span><?= /* @noEscape */ __('Menu')?></span>
                                </strong>
                                <div class="wk-mp-submenu">
                                    <ul>
                                        <?php if ($viewModel->checkPermission("Webkul_Marketplace::add_products") > -1 && $_helper->isAllowed('marketplace/product/add')): ?>
                                            <li class="level-2">
                                                <a href="<?= $escaper->escapeUrl($block
                                                ->getUrl('marketplace/product/add', ['_secure' => $block
                                                ->getRequest()->isSecure()])); ?>">
                                                    <span><?= /* @noEscape */ __('Add Products') ?></span>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                        <?php if ($viewModel->checkPermission("Webkul_Marketplace::product_list") > -1 && $_helper->isAllowed('marketplace/product/productlist')): ?>
                                            <li class="level-2">
                                                <a href="<?= $escaper->escapeUrl($block
                                                ->getUrl('marketplace/product/productlist', ['_secure' => $block
                                                ->getRequest()->isSecure()])); ?>">
                                                    <span><?= /* @noEscape */ __('My Products List') ?></span>
                                                </a>
                                            </li>
                                        <?php endif; ?>
                                        <?php if ($viewModel->checkPermission("Webkul_Marketplace::configurable_attribute") > -1 && $_helper->isAllowed('marketplace/product_attribute/new')): ?>
                                            <?php if (strpos($allow_pro_type, 'configurable') !== false): ?>
                                                <li class="level-2">
                                                    <a href="<?= $escaper->escapeUrl($block
                                                    ->getUrl('marketplace/product_attribute/new', ['_secure' => $block
                                                    ->getRequest()->isSecure()])); ?>">
                                                        <span><?= /* @noEscape */ __('Configurable Attribute') ?></span>
                                                    </a>
                                                </li>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </li>
            <?php endif; ?>
            <?php if ($viewModel->checkPermission("Webkul_Marketplace::customers") > -1 && $_helper->isAllowed('marketplace/account/customer')): ?>
                    <li class="nav item notification-link wk-mp-item-customer level-0 
                    <?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/account/customer')
                    ? "current active":"";?>" id="wk-mp-menu-customer" >
                        <a href="<?= $escaper->escapeUrl($block
                        ->getUrl('marketplace/account/customer/', ['_secure' => $block->getRequest()->isSecure()])); ?>"
                        class="<?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/account/customer')
                        ? "active":"";?>">
                            <span><?= /* @noEscape */ __('Customers') ?></span>
                        </a>
                    </li>
            <?php endif; ?>
            <?php if ($viewModel->checkPermission("Webkul_Marketplace::transactions") > -1 && $_helper->isAllowed('marketplace/transaction/history')): ?>
                <li class="nav item notification-link wk-mp-item-transaction level-0 
                <?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/transaction/history')
                ? "current active":"";?>" id="wk-mp-menu-transaction" >
                    <a href="<?= $escaper->escapeUrl($block
                    ->getUrl('marketplace/transaction/history', ['_secure' => $block
                    ->getRequest()->isSecure()])); ?>" class="<?= /* @noEscape */
                    strpos($magentoCurrentUrl, 'marketplace/transaction/history')? "active":"";?>">
                        <span><?= /* @noEscape */ __('Transactions') ?></span>
                    </a>
                </li>
            <?php endif; ?>
            <?php if ($viewModel->checkPermission("Webkul_Marketplace::earnings") > -1 && $_helper->isAllowed('marketplace/account/earning')): ?>
                <li class="nav item notification-link wk-mp-item-earning level-0
                 <?= /* @noEscape */ strpos($magentoCurrentUrl, 'marketplace/account/earning')
                    ? "current active":"";?>" id="wk-mp-menu-earning" >
                    <a href="<?= $escaper->escapeUrl($block
                    ->getUrl('marketplace/account/earning', ['_secure' => $block
                    ->getRequest()->isSecure()])); ?>" class="<?= /* @noEscape */
                    strpos($magentoCurrentUrl, 'marketplace/account/earning')? "active":"";?>">
                        <span><?= /* @noEscape */ __('Earnings') ?></span>
                    </a>
                </li>
            <?php endif; ?>
            <?= $block->getChildHtml('layout2_seller_account_before_review');?>
   
            <?= $block->getChildHtml('layout2_seller_account_navigation');?>
            <?php if ($viewModel->checkPermission("Webkul_Marketplace::print_pdf_header") > -1 && $_helper->isAllowed('marketplace/order/shipping')): ?>
                <?php if ($_helper->getIsOrderManage()=="1"): ?>
                    <li class="wk-mp-item-order-shipping level-0 <?= /* @noEscape */
                     strpos($magentoCurrentUrl, 'marketplace/order/shipping')
                     ? "current active":"";?>" id="wk-mp-menu-order-shipping" >
                        <a href="<?= $escaper->escapeUrl($block
                        ->getUrl('marketplace/order/shipping', ['_secure' => $block
                        ->getRequest()->isSecure()])); ?>" class="<?= /* @noEscape */
                        strpos($magentoCurrentUrl, 'marketplace/order/shipping')? "active":"";?>">
                            <span><?= /* @noEscape */ __('Print PDF Header') ?></span>
                        </a>
                    </li>
                <?php endif; ?>
            <?php endif; ?>            
            <?= $block->getChildHtml('layout2_seller_account_navigation_settings_menu'); ?>
        <?php else: ?>
            <?= $block->getChildHtml('layout2_seller_account_navigation');?>
            <li class="wk-mp-item-order-shipping level-0 <?= /* @noEscape */
            strpos($magentoCurrentUrl, 'marketplace/account/becomeseller')
            ? "current active":"";?>" id="wk-mp-menu-becomeseller" >
                <a href="<?= $escaper->escapeUrl($block
                ->getUrl('marketplace/account/becomeseller/', ['_secure' => $block
                ->getRequest()->isSecure()])); ?>" class="<?= /* @noEscape */
                strpos($magentoCurrentUrl, 'marketplace/account/becomeseller')? "active":"";?>">
                    <span><?= /* @noEscape */ __('Become Seller') ?></span>
                </a>
            </li>
        <?php endif; ?>
    </ul>
</nav>
<script>
require(["jquery"],function($){
    $(document).ready(function(){
        if(parseInt($(".wk-mp-menu-wrapper").height()) > parseInt($(".wk-mp-page-wrapper").height())){;
            $(".wk-mp-menu-wrapper").css("position", "absolute");
            $(".wk-mp-menu-wrapper").css("top", "0");
        }

        if(parseInt($(".wk-mp-menu-wrapper.fixed").height()) > parseInt($(".wk-mp-page-wrapper").height())){
            $(".wk-mp-menu-wrapper.fixed").css("position", "absolute");
            $(".wk-mp-menu-wrapper.fixed").css("top", "0");
        }

        if(parseInt($(".wk-mp-menu-wrapper").height()) < parseInt($(".wk-mp-page-wrapper").height())){;
            $(".wk-mp-menu-wrapper").css("position", "fixed");
            $(".wk-mp-menu-wrapper").css("top", "auto");
        }

        if(parseInt($(".wk-mp-menu-wrapper.fixed").height()) < parseInt($(".wk-mp-page-wrapper").height())){
            $(".wk-mp-menu-wrapper.fixed").css("position", "fixed");
            $(".wk-mp-menu-wrapper").css("top", "auto");
        }

        document.addEventListener('scroll', function (event) {
            if(parseInt($(".wk-mp-menu-wrapper").height()) > parseInt($(".wk-mp-page-wrapper").height())){
                $(".wk-mp-menu-wrapper").css("top", "0");
                $(".wk-mp-menu-wrapper.fixed").css("top", "0");
            }
            if(parseInt($(".wk-mp-menu-wrapper.fixed").height()) > parseInt($(".wk-mp-page-wrapper").height())){
                $(".wk-mp-menu-wrapper.fixed").css("position", "absolute");
                $(".wk-mp-menu-wrapper.fixed").css("top", "0");
            }

            if(parseInt($(".wk-mp-menu-wrapper").height()) < parseInt($(".wk-mp-page-wrapper").height())){;
                $(".wk-mp-menu-wrapper").css("position", "fixed");
                $(".wk-mp-menu-wrapper").css("top", "0");
            }

            if(parseInt($(".wk-mp-menu-wrapper.fixed").height()) < parseInt($(".wk-mp-page-wrapper").height())){
                $(".wk-mp-menu-wrapper.fixed").css("position", "fixed");
                $(".wk-mp-menu-wrapper").css("top", "0");
            }
        }, true);

        $( document ).ajaxComplete(function( event, request, settings ) {
            if(parseInt($(".wk-mp-menu-wrapper").height()) > parseInt($(".wk-mp-page-wrapper").height())){;
                $(".wk-mp-menu-wrapper").css("position", "absolute");
                $(".wk-mp-menu-wrapper").css("top", "0");
            }

            if(parseInt($(".wk-mp-menu-wrapper.fixed").height()) > parseInt($(".wk-mp-page-wrapper").height())){
                $(".wk-mp-menu-wrapper.fixed").css("position", "absolute");
                $(".wk-mp-menu-wrapper.fixed").css("top", "0");
            }

            if(parseInt($(".wk-mp-menu-wrapper").height()) < parseInt($(".wk-mp-page-wrapper").height())){;
                $(".wk-mp-menu-wrapper").css("position", "fixed");
                $(".wk-mp-menu-wrapper").css("top", "0");
            }

            if(parseInt($(".wk-mp-menu-wrapper.fixed").height()) < parseInt($(".wk-mp-page-wrapper").height())){
                $(".wk-mp-menu-wrapper.fixed").css("position", "fixed");
                $(".wk-mp-menu-wrapper").css("top", "0");
            }
        });
    });
})        
</script>