<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_FormBuilder
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var \Webkul\FormBuilder\Block\Customer\Widget\Telephone $block */
?>

<div class="field telephone required">
    <div class="control">
        <input type="tel"
               name="telephone"
               id="telephone"
               value="<?= $block->escapeHtmlAttr($block->getTelephone()) ?>"
               title="<?= $block->escapeHtmlAttr(__('Contact Number')) ?>"
               class="input-text <?= $block->escapeHtmlAttr(
                   $block->getAttributeValidationClass('telephone')
               ) ?>"
               data-validate="{'validate-custom-phone-no':true}"
        >
        <span class="wk-material-label"><?= $block->escapeHtml(__('Contact Number')) ?></span>
        <div for="phone" class="sign-up help-tip">
            <p><?= __("Please enter the contact number without the country code.

") ?></p>
        </div>
    </div>
</div>
