<div class="page-main" style="width: 100%;">
    <div class="block account-nav" style="width:20%;float:left">
        <!-- <div class="title">
            <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
        </div> -->
        <div class="content">
            <nav class="account-nav">
                <ul class="nav items">
                    <li><a href="<?= $block->getUrl('sidashboard/index/index') ?>">My Account</a></li>
                    <li><a href="<?= $block->getUrl('sidashboard/index/products') ?>" style="color:black;">Products</a></li>
                    <li><a href="<?= $block->getUrl('sipartnerrfq/index/index') ?>">Request For Quote</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="block block-dashboard-info" style="width:80%;float:left">
        <form method="post" action="<?= $block->getUrl('sidashboard/index/saveproduct'); ?>" enctype="multipart/form-data">
            <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />

            <label for="product_name">Product Name:</label>
            <input type="text" id="product_name" name="product_name" required />

            <label for="product_sku">Product SKU:</label>
            <input type="text" id="product_sku" name="product_sku" required />

            <label for="product_price">Product Price:</label>
            <input type="number" id="product_price" name="product_price" required />

            <label for="product_price">Stock Quantity:</label>
            <input type="number" id="stock_qty" name="stock_qty" required />

            <label for="product_description">Product Description:</label>
            <textarea id="product_description" name="product_description" required></textarea>
            
            <label for="product_image">Product Image:</label>
            <input type="file" id="product_image" name="product_image" required />

            <button type="submit">Create Product</button>
        </form>
    </div>
</div>
<style>
    .columns{
        display:flex;
    }
</style>