<!-- <style>
        .solum-st1 {
            background: #f3f2f2;
            padding: 14px;
        }
        .solum-st1 > ul > li
        {
            line-height: 2em;
            text-decoration: none;
        }
       

    </style>
<div class="container" style="padding-top:50px;">
            <div class="solum-st1 sidebar">
                <ul>
                    <li><a href="<?= $block->getUrl('menu/page1') ?>">My Account</a></li>
                    <li><a href="<?= $block->getUrl('menu/page2') ?>">Products</a></li>
                </ul>
            </div>
        </div> -->
<div class="block account-nav">
    <!-- <div class="title">
        <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
    </div> -->
    <div class="content">
        <nav class="account-nav">
            <ul class="nav items">
                <li><a href="<?= $block->getUrl('sidashboard/index/index') ?>">My Account</a></li>
                <li><a href="<?= $block->getUrl('sidashboard/index/products') ?>">Products</a></li>
            </ul>
        </nav>
    </div>
</div>
