<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MarketplaceBaseShipping
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
    // $_helper = $this->helper('Webkul\Marketplace\Helper\Data');
    $helperBlock = $block->getLayout()->createBlock(\Webkul\MarketplaceBaseShipping\Block\Marketplacehelper::class);
    $_helper=$helperBlock->helperObj();
    $isPartner = $_helper->isSeller();
    $isSellerGroup = $_helper->isSellerGroupModuleInstalled();
    $magentoCurrentUrl = $block->getCurrentUrl();
    $viewModel = $block->getViewModel();
    //$helper = $this->helper('Webkul\MpAramexShipping\Helper\Data');
?>
<?php if ($viewModel->checkPermission("Webkul_MarketplaceBaseShipping::shipping_setting") > -1 && $isPartner): ?>
    <?php if (($isSellerGroup && $_helper->isAllowedAction('baseshipping/shipping')) || !$isSellerGroup): ?>
    <li id="wk-mp-menu-base-shipping checking" class="level-2 <?=
        strpos($magentoCurrentUrl, 'baseshipping/shipping')? "current active":"";?>">
        <a href="<?= /* @noEscape */
        $block->getUrl('baseshipping/shipping', ['_secure' => $block->getRequest()->isSecure()]); ?>">
            <span><?= /* @noEscape */  __('Shipping Setting') ?></span>
        </a>
    </li>
<?php endif; ?>
<?php endif; ?>