<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable PHPCompatibility.Miscellaneous.RemovedAlternativePHPTags.MaybeASPOpenTagFound
/** @var \Magento\Wishlist\Block\Customer\Wishlist $block */
?>


<?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()) : ?>
    <?= ($block->getChildHtml('wishlist.rss.link')) ?>
    <form class="form-wishlist-items" id="wishlist-view-form" data-mage-init='{"wishlist":{
          "addToCartUrl":<?= /* @noEscape */ $block->getItemAddToCartParams("%item%") ?>,
          "addAllToCartUrl":<?= /* @noEscape */ $block->getAddAllToCartParams() ?>,
          "commentString":""},
          "validation": {}}' action="<?= $block->escapeUrl($block->getUrl('wishlist/index/update', ['wishlist_id' => $block->getWishlistInstance()->getId()])) ?>" method="post">
          <div class="solumeslrfq-page-header-wrapper">
              <div class="solumeslrfq-page-header">
                  <h2 class="solumeslrfq-title"><?= $escaper->escapeHtml("Wishlist") ?></h2>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <?= $block->getChildHtml('control_buttons') ?>
                    </div>
                </div>
            </div>
            <div class="toolbar wishlist-toolbar remove-pages remove-limiter"><?= $block->getChildHtml('wishlist_item_pager'); ?></div>
            <?= $block->getChildHtml('top') ?>
            <?php if ($block->hasWishlistItems()) : ?>
                <?= $block->getBlockHtml('formkey') ?>
                <?php $block->getChildBlock('items')->setItems($block->getWishlistItems()); ?>
                <div class="mywishlist">
                <?= $block->getChildHtml('items') ?>
            </div>
            <?php else : ?>
                <div class="message info empty"><span><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></span></div>
            <?php endif ?>
            <?= $block->getChildHtml('bottom') ?>
    </form>
    <script id="form-tmpl" type="text/x-magento-template">
        <form id="wishlist-hidden-form" method="post" action="<%- data.url %>" class="no-display">
          <% if (data.qty) { %>
          <input name="qty" value="<%- data.qty %>">
          <% } %>
          
          <% if (data.item) { %>
          <input name="item" value="<%- data.item %>">
          <% } %>
          
          <% if (data.entity) { %>
          <input name="entity" value="<%- data.entity %>">
          <% } %>
      </form>
    </script>
    <div class="toolbar wishlist-toolbar remove-limiter remove-amount"><br><?= $block->getChildHtml('wishlist_item_pager'); ?></div>
<?php endif ?>