<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php $viewModel = $block->getSolumViewModel(); ?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1) :?>
        <?= $block->escapeHtml(
            __(
                '%1 Search result found for "%2"',                
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>',
                $viewModel->getEscapedQueryText()
            ),
            ['span']
        ) ?>
    <?php elseif ($block->getTotalNum() == 1) :?>        
        <?= $block->escapeHtml(
            __(
                '%1 Search result found for "%2"',                
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>',
                $viewModel->getEscapedQueryText()
            ),
            ['span']
        ) ?>
    <?php else :?>
        <?= $block->escapeHtml(
            __('%1 Search result found for "%2"',
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>',
                $viewModel->getEscapedQueryText()
            ),
            ['span']
        ) ?>
    <?php endif; ?>
</p>
