    <style>
        .popup-container {
                display:none;
                width:500px;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.7);
            z-index: 9999;
        }

        .popup-content {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: #fff;
            padding: 20px;
            border-radius: 5px;
        }

        .popup-content h2 {
            margin-top: 0;
        }

        .action-close {
            margin-top: 10px;
        }
        .solum-st1 {
            background: #f3f2f2;
            padding: 14px;
        }
        .solum-st1 > ul > li
        {
            line-height: 2em;
        }
        input[type="text"] {
            padding: 8px;
            width: 300px;
        }
        button {
            padding: 8px;
            width: 44px;
        }
        span.solum-st2 {
            float: left;
            color: #5e5e9a;
            font-size: 12px;
            font-weight: 600;
        }
        span.solum-st3 {
            float: right;
            color: #5e5e9a;
            font-size: 12px;
            font-weight: 600;
        }
        .solum-st4
        {
            font-size: 13px;
            color: #5e5e9a;
            font-weight: 600;
        }

    </style>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js" type="80183920ab0a760d274a4e9e-text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" type="80183920ab0a760d274a4e9e-text/javascript"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->

<div class="container" style="padding-top:90px;">
    <div class="row">
        <div style="width:25%;float:left;">
            <div class="solum-st1">
                <h4>Filter</h4>
                <ul>
                <li>By Product</li>
                <li>By Continent</li>
                <li>By Country</li>
                <li>By POS system</li>
                <li>By Rating</li>
                </ul>
            </div>
        </div>
        <div style="width:75%;float:left;">
            <div class="search-container" style="padding:7px;">
                <form action="#">
                <input type="text" placeholder="Quick Search.." name="search">
                <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </div>
            <div class="row" style="padding-top:20px;">
                <?php $sellers = $block->getSellerPartners(); 
                ?>

                <?php foreach ($sellers as $key=>$seller): ?>
                    <div style="width:25%;float:left;padding:7px;cursor: pointer;padding-bottom:25px;" >
                        <img onclick="openPopup(<?php echo $seller['entity_id']; ?>)" src="https://stage.solumstore.com/media/catalog/product/placeholder/default/product-placeholder_1.png" alt="Product" width="260px" height="auto">
                        <h5 onclick="openPopup(<?php echo $seller['entity_id']; ?>)"><strong><?php echo $seller["business_name"]; ?></strong></h5>
                        <p class="solum-st4" style="height: 1.2em;" onclick="openPopup(<?php echo $seller['entity_id']; ?>)"><?php echo $seller["contact_info"]; ?></p>
                        <div>
                            <span class="solum-st2"><i class="fa fa-star"></i><?php  echo $seller["credit_ratings"]; ?>/5</span>
                            <span class="solum-st3"><a href="<?php echo $this->getUrl('productlist', ['id' => $seller['entity_id']]); ?>" style="background-color: #1979c3;padding: 6px 9px 6px 9px;border-radius: 5px;color: white;">Buy</a></span>
                            <div class="popup-container" id="sipartnePopup<?php echo $seller["entity_id"]; ?>" style="cursor:pointer;">
                                <div class="popup-content">
                                    <h2>Seller Details</h2>
                                    <p><strong>Name:</strong> <?php echo $seller["business_name"]; ?></p>
                                    <p><strong>Email:</strong> <?php echo $seller["email"]; ?></p>
                                    <!-- Add more seller details as needed -->
                                    <button class="action-close" onclick="closePopup(<?php echo $seller['entity_id']; ?>)">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>


<script>
  function openPopup(id) {
    var popup = document.getElementById('sipartnePopup'+id);
    popup.style.display = 'block';
}

function closePopup(id) {
    var popup = document.getElementById('sipartnePopup'+id);
    popup.style.display = 'none';
}
</script>
