<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_FormBuilder
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

 // Webkul\FormBuilder\Block\Adminhtml\ViewResponse; Block File

$data   = $block->getFormInfoById();
$locale = $block->getLocale();
$responses   = $block->jsonDecode($data['forms_response']);

?>
<div class="page-main-actions">
    <div class="page-actions-placeholder" style=""></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner" data-title="Submitted Data #5">
            <div class="page-actions-buttons">
                <button id="" title="Back" type="button" class="action-default scalable back"
                    style="background: #373330;color: #f7f3eb;"
                    onclick="setLocation('<?=  /**  @escapeNotVerified  **/
                    $block->getUrl('formbuilder/response/index/'); ?>')"
                    data-ui-id="page-actions-toolbar-back-button">
                    <span><?= $block->escapeHtml(__("Back")) ?></span>
                </button>
                <button id="wk-response-delete" title="delete" type="button" class="action-default scalable delete"
                    style="background: #eb5202;color: white;"
                    data-ui-id="page-actions-toolbar-delete-button">
                    <span><?= $block->escapeHtml(__("Delete")) ?></span>
                </button>
            </div>
        </div>
    </div>
</div>

<div id="page:main-container" class="page-columns">
    <div class="admin__old">
        <div id="container" class="main-col">
            <section class="admin__page-section request-view-information">
                <div class="admin__page-section-title">
                    <span class="title"><?= $block->escapeHtml(__('Information')) ?></span>
                </div>
                <div class="admin__page-section-content">
                    <table class="admin__table-secondary request-information-table">
                        <tbody>
                            <tr>
                                <th><?= $block->escapeHtml(__("Submitted At")) ?></th>
                                <td><?= $block->escapeHtml($block->getTimeAccordingToTimeZone($data['created_at'])); ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__("IP Address")) ?></th>
                                <td><?= $block->escapeHtml($data['user_ip']); ?></td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__("Customer")) ?></th>
                                <td>
                                    <?= !empty($data['user_id'])
                                    ? $block->escapeHtml($block->getUserNameById($data['user_id']))
                                    : $block->escapeHtml(__('Guest')); ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__("Store")) ?></th>
                                <td><?= $block->escapeHtml($block->getStoreNameById($data['store_id'])); ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </section>
            <section class="admin__page-section request-view-data">
                <div class="admin__page-section-title">
                    <span class="title"><?= $block->escapeHtml(__("Data")) ?></span>
                </div>
                <div class="admin__page-section-content">
                    <?php if (isset($responses) && !empty($responses)) { ?>
                    <table class="admin__table-secondary request-information-table">
                        <tbody>
                            <?php  foreach ($responses as $key => $response) {?>
                            <tr>
                                <th><?= (isset($response->label) ? $block->escapeHtml($response->label) : ''); ?></th>
                                <td>
                                    <?php if (isset($response->value) && is_array($response->value)) { ?>
                                        <?= (isset($response->value) ?
                                        $block->escapeHtml(implode(",", $response->value)) :
                                        $block->escapeHtml(__("No Data"))); ?>
                                    <?php } else { ?>
                                        <?= (isset($response->value) && !empty($response->value)
                                            ?  /**  @escapeNotVerified  **/ ($response->value)
                                            : $block->escapeHtml(__("No Data"))); ?>
                                    <?php }?>

                                    <?php if ($key == "wk_file") { ?>
                                        <?php if (isset($response->value)) { ?>
                                            <a target="2"
                                                href="<?= /* @escapeNotVerified */
                                                $block->escapeHtml($block->getMediaPath())
                                                ."FormBuilder/Media/".$block->escapeHtml($response->value);?>">
                                                <?=  $block->escapeHtml(__('View')) ?>
                                        <?php } ?>
                                        
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                    <?php } else { ?>
                    <p> <?= $block->escapeHtml(__(" No Data")); ?> </p>
                    <?php } ?>
                </div>
            </section>
        </div>
    </div>

    <script>
    require([
        "jquery",
        "mage/translate",
    ], function ($) {
        $('#wk-response-delete').click(function(){
            var result = confirm("Want to delete?");
            if (result) {
                window.location.href = ('<?=  /**  @escapeNotVerified  **/
                    $block->getUrl('formbuilder/response/delete/', ['entity_id'=>$data['entity_id']]); ?>')
            }else{
                return false;
            }
        });
    });
</script>