<!-- <a href="<?= $block->getUrl('sipartnerrfq/index/insert'); ?>" style="background-color: #1979c3;padding: 6px 9px 6px 9px;border-radius: 5px;color: white;">Create Product</a> -->
<div class="page-main" style="width: 100%;">
    <div class="block account-nav" style="width:20%;float:left">
        <!-- <div class="title">
            <strong><?= $block->escapeHtml(__('My Account')) ?></strong>
        </div> -->
        <div class="content">
            <nav class="account-nav">
                <ul class="nav items">
                    <li><a href="<?= $block->getUrl('sidashboard/index/index') ?>" >My Account</a></li>
                    <li><a href="<?= $block->getUrl('sidashboard/index/products') ?>" >Products</a></li>
                    <li><a href="<?= $block->getUrl('sipartnerrfq/index/index') ?>" style="color:black;">Request For Quote</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="block block-dashboard-info" style="width:80%;float:left">
        <table class="view-table">
            <thead>
                <tr>
                    <th>Customer Name</th>
                    <th>Status</th>
                    <th>Message</th>
                    <th>No Of Stores</th>
                    <th>Quantity Per Store</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php
                $collectionData = $block->getData();
                foreach($collectionData as $collection):
                ?>
                        <tr>
                            <td><?= $collection['customer_id'] ?></td>
                            <td><?= $collection['status'] ?></td>
                            <td><?= $collection['comment'] ?></td>
                            <td><?= $collection['no_of_stores'] ?></td>
                            <td><?= $collection['quantity_per_store'] ?></td>
                            <!-- <td><img src="" alt="" width="50" height="100"></td> -->
                            <td><a href="<?php echo $this->getUrl('sipartnerrfq/index/edit', ['id' => $collection['entity_id']]); ?>">Edit</a></td>
                        </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<style>
    .columns{
        display:flex;
    }
.view-table {
    width: 100%;
    border-collapse: collapse;
}

.view-table th,
.view-table td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

.view-table th {
    background-color: #f2f2f2;
    font-weight: bold;
}
</style>