<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
?>
<div class="wk-mp-design">
    <div class="fieldset wk-mp-customer-tabs-fieldset">
        <div class="page-title-wrapper-heading">
            <legend class="legend wk-mp-top-heading-legend">
                <span><?=/* @noEscape */ __("Customers")?></span>    
            </legend>
        </div>
    </div>
</div>
<?=/* @noEscape */ $block->getChildHtml("marketplace_customers_listing");?>