<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
/** @var $block \Webkul\Marketplace\Block\Page\Header */
$helper = $block->getHelper();
?>

<?php  if ($block->getShowPart() == "logo") {?>
        <span class="wk-mp-logo">
            <a
                href="<?= /* @escapeNotVerified */ $escaper->escapeUrl($block->getBaseUrl()) ?>">
                <span class="wk-mp-logo-img-wrapper">
                    <img class="wk-mp-logo-img" src="<?= $escaper
                    ->escapeUrl($block->getSellerDashboardLogoSrc())?>" 
                    alt="<?= $escaper->escapeHtml(__('Seller Panel')) ?>"/>
                </span>
            </a>
        </span>    
        <a href="#" onclick="return false;" class="solumels_silder_icon open"></a>
<?php } ?>

<?php  if ($block->getShowPart() == "user") {?>
    <?php
        $logo = $block->getSellerLogo();
        if(!empty($logo)){
            $logo = $helper->getMediaUrl().'avatar/'.$logo;
        }
    ?>
        <div class="wk-mp-user wk-mp__action-dropdown-wrap">
            <a
                href="#"
                onlick="return false;"
                class="wk-mp__action-dropdown"
                title="<?= $escaper->escapeHtml(__('My Account')) ?>"
                data-mage-init='{"dropdown":{}}'
                data-toggle="dropdown">
                <span class="wk-mp-seller-header-logo-wrapper">
                    <?php if(!$logo){?>
                        <div class="circle">
                            <p class="circle-inner"><?= strtoupper(substr($block->getSellerShopName(), 0, 1)); ?></p>
                        </div>
                    <?php } else {?>
                        <img class="wk-mp-seller-header-logo" src="<?= $escaper->escapeUrl($logo)?>"
                        alt="<?= $escaper->escapeHtml(__('Seller Panel')) ?>"/>
                     <?php } ?>
                </span>
                <span class="wk-mp__action-dropdown-text">
                    <span class="wk-mp-user-account-text">
                        <span class="wk-mp-user-account-text-wrapper">
                            <?php /** $escaper->escapeHtml($block->getSellerShopName()); */ ?>
                        </span>
                    </span>
                </span>
            </a>
            <ul class="wk-mp__action-dropdown-menu">
                <li class="wk-mp-dropdown-menu-settings">
                    <a
                        href="<?= /* @escapeNotVerified */ $escaper->escapeUrl($block
                        ->getUrl('marketplace/account/editprofile')) ?>"
                        <?= /* @escapeNotVerified */ $escaper->escapeHtml($block
                        ->getUiId('user', 'account', 'settings'))?>
                        title="<?= $escaper->escapeHtml(__('Account Setting')) ?>">
                        <?= /* @escapeNotVerified */ $escaper->escapeHtml(__('Account Setting')) ?>
                    </a>
                </li>
                <li class="wk-mp-dropdown-menu-buyer">
                    <a
                        href="<?= /* @escapeNotVerified */ $escaper->escapeUrl($block
                        ->getUrl('customer/account')); ?>"
                        title="<?= $escaper->escapeHtml(__('Buyer Dashboard')); ?>"
                        target="_blank" class="store-front">
                        <?= /* @escapeNotVerified */ $escaper->escapeHtml(__('Buyer Dashboard')); ?>
                    </a>
                </li>
                <li class="wk-mp-dropdown-menu-logout">
                    <a
                        href="<?= /* @escapeNotVerified */ $escaper->escapeUrl($block
                        ->getUrl('customer/account/logout')) ?>"
                        class="wk-mp-account-logout"
                        title="<?= $escaper->escapeHtml(__('Logout')) ?>">
                        <?= /* @escapeNotVerified */ $escaper->escapeHtml(__('Logout')) ?>
                    </a>
                </li>
            </ul>
        </div>
<?php } ?>

<?php if ($block->getShowPart() == "seller.notifications") {?>
    <?php $totalCount = $block->getAllNotificationCount(); ?>
        <div class="wk-mp-notification wk-mp__action-dropdown-wrap">
            <a
                onlick="return false;"
                href="#"
                class="wk-mp__action-dropdown"
                <?php if ($totalCount): ?> data-mage-init='{"dropdown":{}}' <?php endif; ?> >
                <span class="wk-mp-notification-icon"></span>
                <?php if ($totalCount): ?>
                    <?php if ($totalCount > 5): ?>
                        <span class="wk-mp-notification-count">5+</span>
                    <?php else: ?>
                        <span class="wk-mp-notification-count">
                            <?= $escaper->escapeHtml($totalCount); ?>
                        </span>
                    <?php endif; ?>
                <?php endif; ?>
            </a>
            <?php if ($totalCount): ?>
                <ul class="wk-mp__action-dropdown-menu">
                    <?php foreach ($block->getAllNotification() as $notification) {
                        /* @noEscape */ echo $block->getNotificationInfo($notification);
                    } ?>
                    <li>
                        <small>
                            <a href="<?= $escaper->escapeUrl($block
                            ->getUrl('marketplace/account/notification'))?>">
                                <?= $escaper->escapeHtml(__("View All"))?>
                            </a>
                        </small>
                    </li>
                </ul>
            <?php endif; ?>
        </div>
<?php } ?>

<?php if ($block->getShowPart() == "seller.home") {?>
    <div class="wk-mp-home wk-mp__action-dropdown-wrap">
        <a
            href="<?= $escaper->escapeUrl($block->getUrl(''))?>"
            class="wk-mp__action-dropdown">
        </a>
    </div>
<?php } ?>

<?php if ($block->getShowPart() == "other") {?>
    <?= $block->getChildHtml(); ?>
<?php } ?>
<script>
    require(["jquery"], function($){
        $(document).on("click", ".solumels_silder_icon.open", function(){
            var text = $(this).attr("class");
            if (text.includes("open")) {
                $(".wk-mp-menu .level-0 a span").css("display", "none");
                $(".wk-mp-logo").css("visibility", "hidden");
                $(this).removeClass("open");
                $(this).addClass("close");
                $(".wk-mp-menu-wrapper").addClass("close");
                $(".wk-mp-page-wrapper").addClass("close");
            }         
        });
        $(document).on("click", ".solumels_silder_icon.close", function(e){
            var text = $(this).attr("class");
            if (text.includes("close")){
                $(".wk-mp-menu .level-0 a span").css("display", "block");
                $(".wk-mp-logo").css("visibility", "visible");
                $(this).removeClass("close");
                $(this).addClass("open");
                $(".wk-mp-menu-wrapper").removeClass("close");
                $(".wk-mp-page-wrapper").removeClass("close");
            }
        });
    })
</script>