<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MpMassUpload
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$profiles = $block->getProfiles();
?>
<div class="wk-massupload-container">
        <fieldset class="fieldset">
            <?= $block->getBlockHtml('formkey') ?>
            <?= $block->getBlockHtml('seller.formkey')?>
            <div class="field required">
                <label class="label">
                    <span><?= $block->escapeHtml(__("Select Profile")); ?></span>
                </label>
                <div class="control">
                    <select data-validate="{'validate-select':true}"
                        title="Profile"
                        class="required-entry"
                        id="profile"
                        name="profile"
                        aria-required="true">
                        <?php foreach ($profiles as $profileId => $name): ?>
                            <option value="<?= $block->escapeHtml($profileId); ?>">
                                <?= $block->escapeHtml($name); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <button id="run-profile" class="button wk-mp-btn primary-btn rounded line-height-15" type="submit">
                <span><span><?= $block->escapeHtml(__("Run Profile")); ?></span></span>
            </button>
        </fieldset>
    </div>