<html>
<head>
	<style>
	/* body{width:600px;font-family:calibri;} */
	.error {color:#FF0000;}
	.chat-connection-ack{color: #26af26;}
	.chat-message {border-bottom-left-radius: 4px;border-bottom-right-radius: 4px;
	}
	#btnSend {background: #26af26;border: #26af26 1px solid;	border-radius: 4px;color: #FFF;display: block;margin: 15px 0px;padding: 10px 50px;cursor: pointer;
	}
	#chat-box {background: #fff8f8;border: 1px solid #ffdddd;border-radius: 4px;border-bottom-left-radius:0px;border-bottom-right-radius: 0px;min-height: 300px;padding: 10px;overflow: auto;
	}
	.chat-box-html{color: #09F;margin: 10px 0px;font-size:0.8em;}
	.chat-box-message{color: #09F;padding: 5px 10px; background-color: #fff;border: 1px solid #ffdddd;border-radius:4px;display:inline-block;}
	.chat-input{border: 1px solid #ffdddd;border-top: 0px;width: 100%;box-sizing: border-box;padding: 10px 8px;color: #191919;
	}
	.main-contact-list{width:25%;float:left}
	.main-chat-box{width:25%;float:left}
	.list-group-item{list-style-type: none;cursor:pointer	}
	#cheader .uavatar {
	    width: 50px;
	    height: 50px;
	    align-self: center;
	    border-radius: 50%;
	    border: 3px solid #808080c2;
	    display: flex;
	    justify-content: center;
	    text-align: -webkit-auto;
	}
	.convo-right{
		padding:1em .5em;
		margin-left: calc(20%);
		direction: rtl;
		margin-bottom:5px;
		display: flex;
	}
	.convo-left{
		padding:1em .5em;
		margin-bottom:5px;
		display: flex;
	}
	.convo img{
		max-width: calc(100%);
	    border-radius: 100%;
		max-height:calc(100%);
	}
		.convo .img {
	    width: 50px;
	    height: 50px;
	    align-self: center;
	    border-radius: 50%;
	    border: 3px solid #808080c2;
	    display: flex;
	    justify-content: center;
	    text-align: -webkit-auto;
	}
	.convo-left .img{
		font-size: 30px;
		font-weight: bold;
		background-color: #5057a8;
		color: white;
	}

	.convo-right .img{
		font-size: 30px;
		font-weight: bold;
		background-color:#339bc3;
		color: white;
	}
	.convo{
		position: relative;
		width: calc(80%);

	}
	.convo .adminMessage {
	    max-width: calc(80%);
	    border-radius: 15px;
		overflow-wrap: break-word;
	}
	.convo-left .adminMessage {
	    background: #a6a6af;
	    margin-left: 10px;
	     padding: 1em;
	    color: white;
	}
	.convo-right .adminMessage {
	    background: #2031ff;
	    margin-right: 10px;
	    padding: 1em;
	    color: white;
	}
	small.status {
    position: absolute;
    bottom: 0;
    font-style: italic;
}
.convo-left .status {
    left: 5rem;
	  
	}
	.convo-right .status {
    right: 5rem;
	  
	}
	div#nw_msg {
		display: none;
    position: absolute;
    z-index: 10;
    background: #00a1ff;
    top: calc(79%);
    right: 30px;
    color: white;
    padding: .5em;
    border-radius: 10px;
    cursor: pointer;
}

	</style>	
	<script type="text/javascript">
		
		var selectedCustomerDetails={};
		var allCustomers=[];
		require(['jquery'], function($) {
			// $.ajax({
			// 	method: "GET",
			// 	url: "<?php  echo $block->getUrl('adminlivechat/grid/loadconversation'); ?>",
			// 	data: { q:'' },
			// 	})
			// .done(function( data ) {
			// 	$("#convo-list").html("");
			// 	var allCustomers=[];
			// 	for(var i=0;i<data.length;i++){
			// 		allCustomers.push({id:data.user_id,user_name:data.user_name})
			// 		$("#convo-list").append('<li class="list-group-item load-chat w-100" style="height: 30px;" data-thread-id="'+data[i].id+'" data-user-id="'+data[i].user_ids+'"><table class="" width="100%"><tr><td width="10%"><div class="uavatar"><span style="background-color: cadetblue; padding: 2px 7px 2px 7px;border-radius: 50%;margin-right:5px;margin-bottom:7px;color:white">'+data[i].user_name.charAt(0).toUpperCase()+'</span></div></td>	<td><span class="uname">'+data[i].user_name+'</span><span class="badge badge-danger float-right notif"></span></td></tr></table></li>');
			// 	}
			// //do your thing

			// });
			function showMessage(messageHTML) {
				$('#chat-box').append(messageHTML);
			}

			$(document).ready(function(){
				var websocket = new WebSocket("ws://localhost:8090/php-socket.php"); 
				websocket.onopen = function(event) { 
					// showMessage("<div class='chat-connection-a	ck'>Connection is established!</div>");		
				}
				
				websocket.onerror = function(event){
					// showMessage("<div class='error'>Problem due to some Error</div>");
				};
				websocket.onclose = function(event){
					// showMessage("<div class='chat-connection-ack'>Connection Closed</div>");
				}; 
				$(document).on('click', '.load-chat', function() {
					allCustomers.filter(function (e) {
						if(e.entity_id==userId){
							selectedCustomerDetails={id:userId,user_name:e.firstname+' '+e.lastname}
						}
				});
					var threadId = $(this).data('thread-id');
					var userId = $(this).data('user-id');
					$('#chat-box').html('')
					$.ajax({
						method: "GET",
						url: "<?php  echo $block->getUrl('adminlivechat/grid/loadchat'); ?>",
						data: { threadId:threadId,userId:userId },
						})
					.done(function( data ) {
						// $("#convo-list").html("");
						for(var i=0;i<data[0].length;i++){
							var className = '<?php echo $block->getCustomerId(); ?>' == data[0][i].id ? 'convo-right' : 'convo-left';
							var userName = '<?php echo $block->getCustomerId(); ?>' == data[0][i].id ? data[1][1].firstname+' '+data[1][1].lastname : data[1][0].firstname+' '+data[1][0].lastname;
							$('#chat-box').append('<div class="convo '+className+'"><div class="img"><span>'+userName.charAt(0).toUpperCase()+'</span></div><div class="adminMessage">'+data[0][i].message+'</div><small class="status" data-id="1">'+userName+'</small></div>');
							// $("#convo-list").append('<li class="list-group-item load-chat w-100" data-thread-id="'+data[i].id+'"><table class="" width="100%"><tr><td width="10%"><div class="uavatar"><img src="" alt="ew"></div></td>	<td><span class="uname">'+data[i].user_name+'</span><span class="badge badge-danger float-right notif">0</span></td></tr></table></li>');
						}
					});
				});
				websocket.onmessage = function(event) {
					var Data = JSON.parse(event.data);
					console.log(Data);
					if(Data.chat_message)
						if(Data.chat_user== selectedCustomerDetails){
							var className = 'convo-left';
							var userName = selectedCustomerDetails.user_name
							$('#chat-box').append('<div class="convo '+className+'"><div class="img"><span>'+userName.charAt(0).toUpperCase()+'</span></div><div class="adminMessage">'+Data.chat_message+'</div><small class="status" data-id="1">'+userName+'</small></div>');

							// showMessage("<div class='"+Data.chat_user+"'>"+Data.chat_message+"</div>")
						}
							
					// $('#chat-box').append();
					$('#chat-message').val('');
				};
				// $("#chat-user").change(function(){
				// 	$('#chat-user').attr("type","hidden");		
				// 	var messageJSON = {
				// 		chat_user: $('#chat-user').val(),
				// 		chat_message: $('#chat-message').val()
				// 	};
				// 	websocket.getData(JSON.stringify(messageJSON));
				// });
				$('#chat-user').attr("type","hidden");
				$('#frmChat').on("submit",function(event){
					event.preventDefault();
					$('#chat-user').attr("type","hidden");		
					var messageJSON = {
						chat_user: $('#chat-user').val(),
						chat_message: $('#chat-message').val()
					};
					websocket.send(JSON.stringify(messageJSON));
					$.ajax({
						method: "GET",
						url: "<?php  echo $block->getUrl('customerlivechat/index/savechat'); ?>",
						data: { message:$('#chat-message').val(),userId:$('#chat-user').val() },
						})
					.done(function( data ) {
						
					});
				});
			});
		});


	</script>
	</head>
	<body>
		<div class="main-content">
			<!-- <div class="main-contact-list">
				<div class="col-lg-12">
					<div class="row">
						<form action="" id="filter-contact" class=" w-100">
							<div class="form-group" id="filter-row">
								<input type="text" class="form-control" placeholder="Search user here" id="find_user">
								<div id="filtered-field" style="display: none">
									
								</div>
							</div>
						</form>
					</div>

				</div>
				<ul class="list-group" style="margin-top:7px;" id="convo-list">
				</ul>
			</div> -->
			<div class="main-chat-box">
				<form name="frmChat" id="frmChat">
					<div id="chat-box"></div>
					<input type="text" name="chat-user" id="chat-user" placeholder="Name" value="<?php echo $block->getCustomerId(); ?>" class="chat-input" required />
					<input type="text" name="chat-message" id="chat-message" placeholder="Message"  class="chat-input chat-message" required />
					<input type="submit" id="btnSend" name="send-chat-message" value="Send" >
				</form>
			</div>
		</div>
</body>
</html>